### ISSUE TITLE
Hide/remove the "New upload" button on the download page

### ISSUE THREAD

**Issue by shimikano** [psi-4ward/psitransfer#112]
Thank you for this nice tool!

Is there a way to optionally have the "New upload" button removed on the download page?

That button doesn't seem to be part of [`download.pug`](https://github.com/psi-4ward/psitransfer/blob/cc689b981b569bbd5969ae9c2509880f828f1877/public/pug/download.pug) (which could easily be edited), but is defined in [`Download.vue`](https://github.com/psi-4ward/psitransfer/blob/cc689b981b569bbd5969ae9c2509880f828f1877/app/src/Download.vue#L3).

I know that one can set a password to protect uploads (`uploadPass`), but we'd like to completely hide the button in order not to confuse users.

**Comment by psi-4ward** [comment]
What about to inject a little css with display none?

**Comment by shimikano** [comment]
Thanks for getting back.

I thought about that also. However, being on Docker, I wasn't able to find an easy way to "inject" additional CSS styles.

I guess I could - in analogy to `download.pug` and `upload.pug` - mount a copy of `public/assets/styles.css` with the customizations into the container, but, unlike the simple `.pug` templates, that would be quite a bit of duplication.

Is there an easier way to add custom CSS styles using the Docker image?

For reference, this would be the docker-compose file:

```yml
version: "3.5"

services:
  psitransfer:
    container_name: psitransfer
    image: psitrax/psitransfer:2.0.0
    ports:
      - "3000"
    volumes:
      - data:/data
      - ./config.production.js:/app/config.production.js
      - ./upload.pug:/app/public/pug/upload.pug
      - ./download.pug:/app/public/pug/download.pug
      - ./styles.css:/app/public/assets/styles.css

volumes:
  data:
```
