### ISSUE TITLE
Feature request: Add /download subdirectory variable to URL

### ISSUE THREAD

**Issue by modem7** [psi-4ward/psitransfer#136]
I would like the ability to add a subdirectory for file downloads. 

E.g. I have my Psitransfer set up on files.mydomain.com. 

Currently, when getting the link to files for users to download, this goes to files.mydomain.com/<bucketID>.

Would it be possible to have it so it's files.mydomain.com/download/<bucketID> (the "downloads" value is just an example). 

This would allow us to secure files.mydomain.com and files.mydomain.com/admin with 2fa/basic HTTP auth, and leave /download with no auth, further securing file transfers and reducing chances of bruteforce attacks

**Comment by modem7** [comment]
I've tried setting an environmental variable, but either I've done it wrong, or something isn't working:

```
  psitransfer:
    container_name: Psitransfer
    restart: unless-stopped
    image: psitrax/psitransfer:latest
    security_opt:
      - no-new-privileges:true
    environment:
      PSITRANSFER_UPLOAD_PASS: $PSITRANSFER_UPLOAD_PASS
      PSITRANSFER_ADMIN_PASS: $PSITRANSFER_ADMIN_PASS
      PSITRANSFER_UPLOADAPPPATH: /upload
    networks:
      pihole:
        ipv4_address: '172.22.0.124'
    volumes:
      - $USERDIR/Psitransfer/data:/data
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.psitransfer-rtr.entrypoints=https"
      - "traefik.http.routers.psitransfer-admin.entrypoints=https"
      - "traefik.http.routers.psitransfer-rtr.rule=Host(`files.$DOMAINNAME`)"
      - "traefik.http.routers.psitransfer-admin.rule=Host(`files.$DOMAINNAME`) && Path(`/admin`)"
      - "traefik.http.routers.psitransfer-admin.tls=true"
      - "traefik.http.routers.psitransfer-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.psitransfer-rtr.middlewares=chain-no-auth@file"
      - "traefik.http.routers.psitransfer-admin.middlewares=chain-authelia@file" # Authelia for Admin
      ## HTTP Services
      - "traefik.http.routers.psitransfer-rtr.service=psitransfer-svc"
      - "traefik.http.services.psitransfer-svc.loadbalancer.server.port=3000"
```
