### ISSUE TITLE
Traefik and Swarm - Use case

### ISSUE THREAD

**Issue by David-COUDRAY** [psi-4ward/psitransfer#269]
Hi,

I try to use PSITranfer with Docker Swarm and Traefik.

This is my docker compose file : 
```
version: "3"
services:
  app:
    image: psitrax/psitransfer:latest
    volumes:
      - data:/data
    environment:
      - PSITRANSFER_ADMIN_PASS=xxx
      - PSITRANSFER_DEFAULTRETENTION=3600
      - PSITRANSFER_DEFAULT_LANGUAGE=fr
    deploy:
      placement:
        constraints:
          - node.role == worker
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-net
        - traefik.constraint-label=xxxxxx
        - traefik.http.routers.psitransfer-https.rule=Host('test.domain.com')
        - traefik.http.routers.psitransfer-https.entrypoints=https
        - traefik.http.routers.psitransfer-https.tls=true
        - traefik.http.routers.psitransfer-https.tls.certresolver=le
        - traefik.http.routers.psitransfer-https.service=psitransfer
        - traefik.http.services.psitransfer.loadbalancer.server.port=3000

networks:
  traefik-net:
    external: true
volumes:
  data:
    driver: local
```

When I access to https://test.domain.com, I've an error: `Gateway Timeout`

And on traefik log, I get 504 after 30s.
```
10.0.0.2 - - [21/Apr/2023:10:00:11 +0000] "GET / HTTP/2.0" 499 21 "-" "-" 5073 "psitransfer-https@docker" "http://10.0.3.3:3000" 19561ms
10.0.0.2 - - [21/Apr/2023:10:00:30 +0000] "GET / HTTP/2.0" 504 15 "-" "-" 5074 "psitransfer-https@docker" "http://10.0.3.3:3000" 30001ms
```

Do you have an idea how to work with traefik and swarm ?

Also, how I can mount, with named volume, the config.js ?
