### ISSUE TITLE
Ansible

### ISSUE THREAD

**Issue by martin-braun** [psi-4ward/psitransfer#309]
The "Manual, from source" steps could be incorporated into an Ansible script. I used to do this for Directus deployments and it should be pretty straight forward if we limit ourselves to Debian.

Reasons for this:

- No docker, not everyone likes docker, it's just another layer, especially when using Proxmox
- Easier updates, since Ansible deployments can be written in a way that rolls over, it's just a simple redeployment
- Mass deployment, since an inventory file with many hosts can be provided, this is handy when you want to keep public and private password protected instances as well as personal and work-related environments apart

I'm making this issue to see if someone else is interested in this?

**Comment by lpirl** [comment]
Great idea.

It is probably hard to create a role that fits the taste of everyone, but if we don't try, we don't know.

I use the following quick-and-dirty role for *updating* a small deployment. Initial installation would need some more steps, as installing npm, etc.

```yml
# file: <role_name>/defaults/main.yml

file_transfer_app_user_name: file-transfer
```

```yml
# file: <role_name>/tasks/main.yml

- name: create user for file transfer app
  register: create_file_transfer_app_user_result
  user:
    name: "{{ file_transfer_app_user_name }}"
    comment: "user for running the file transfer Web app"
    group: www-data



- name: reset PsiTransfer sources
  register: git_checkout
  command: git checkout .
  args:
    chdir: >-
      {{ create_file_transfer_app_user_result.home }}/psitransfer
  changed_when: "'Updated 0 paths' not in git_checkout.stderr"
  become_user: "{{ file_transfer_app_user_name }}"

- name: update PsiTransfer sources
  register: git_pull
  command: git pull
  args:
    chdir: >-
      {{ create_file_transfer_app_user_result.home }}/psitransfer
  changed_when: "'is up to date' not in git_pull.stdout"
  become_user: "{{ file_transfer_app_user_name }}"



- name: build
  command: "{{ item.cmd }}"
  args:
    chdir: "{{ item.dir }}"
  with_items:
    - cmd: npm install
      dir: "{{ create_file_transfer_app_user_result.home }}/psitransfer/app"
    - cmd: npm run build
      dir: "{{ create_file_transfer_app_user_result.home }}/psitransfer/app"
    - cmd: npm install
      dir: "{{ create_file_transfer_app_user_result.home }}/psitransfer"

  become_user: "{{ file_transfer_app_user_name }}"
  when: git_pull.changed



- name: restart file transfer app
  service:
    name: psitransfer
    state: restarted
  when: git_pull.changed
```

Could maybe serve as a starting point.
