### ISSUE TITLE
[Bug?] Issues with file permissions

### ISSUE THREAD

**Issue by back-lacking** [psi-4ward/psitransfer#331]
So I have a PsiTransfer instance on a VPS incase I need to send something to someone, and its been working fine for the few times that I've needed to use it. 
However, recently its been stuck on uploading, and the progress bar doesn't move. 
Looking at the docker logs, I would get a permission error like this
```bash
2025-03-17T04:47:33.525Z POST /files 500 1.994 172.19.0.4
Error: EACCES: permission denied, mkdir '/data/023f04aff393'
```
So far, I've tried making the data directory owned by my normal ubuntu user rather than root  (was done by doing `sudo chown ubuntu:ubuntu -R ./data`). I rebooted the container afterwards, and got the same error in the logs. 

Not really sure whats going on, and why it decided to randomly get a file permission issue. 
My current docker-compose
```yaml
services:
  psitransfer:
    container_name: psitransfer
    environment:
      - PSITRANSFER_ADMIN_PASS=adminpass
    volumes:
      - ./data:/data
    image: psitrax/psitransfer
    ports:
      - 3000:3000
    networks:
      - nginx-pm-plus
networks:
  nginx-pm-plus:
    external: true
```
