### ISSUE TITLE
List of enviromet variables for docker install

### ISSUE THREAD

**Issue by BobTB** [psi-4ward/psitransfer#78]
Is there a list ofenviroment variables for psitransfer, to see what we can be set using  docker ? 

How to make the /admin page work in docker setup?

**Comment by rgstephens** [comment]
Love this project!

I prefer using docker-compose and having config files stored outside of the container.  Here's my `docker-compose.yml`. I've copied the `config.js` from the root of the projected and added my admin password in there.

I would also like to have the node log written outside the container. Will set that up another day.

```
version: "3.4"

services:
  psitransfer:
    image: psitransfer
    container_name: psitransfer
    ports:
      - 3000:3000
    volumes:
      - ./data:/data
      - ./config.js:/app/config.js
```
